sudo: required

services:
  - docker
  - maven

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt-get install maven
  - sudo apt-get install openjdk-17-jdk
  - docker build -t dauren/sweetfit .

scripts:
  - docker run dauren/sweetfit
