sudo: required

services:
  - docker
  - maven
  - openjdk-17-jdk

before_install:
  - sudo apt-get update
  - sudo apt-get install maven
  - sudo apt-get install openjdk-17-jdk
  - docker build -t dauren/sweetfit .

scripts:
  - docker run dauren/sweetfit
