server:
  port: 9000

spring:
  application:
    name: retopay
    environment: ${ENVIRONMENT:local}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB
  jmx:
    default-domain: retopay
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/sweet}
    username: ${DB_USERNAME:sweet}
    password: ${DB_PASSWORD:sweet}

  liquibase:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/sweet}
    user: ${DB_USERNAME:sweet}
    password: ${DB_PASSWORD:sweet}
    liquibase-schema: ${LIQUIBASE_SCHEMA:public}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        generate_statistics: false
        default_schema: public

  mail:
    host: smtp.gmail.com
    port: 587
    username: daurenlanguage@gmail.com
    password: sbqukunzuvwylwmp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true
          required: true





jwt:
  secret: ${JWT_SECRET:dauren}

mobizon:
  url: ${MOBIZON_URL:api.mobizon.kz}
  apiKey: ${MOBIZON_API_KEY:kza751b7c8b1f9dd9e9c3d862901789f677dc7c295b3725e650d0c51d5d355fcf2a7b9}




